name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test hello-ld-preload
      run: cd hello-ld-preload && ./test.sh
    - name: Test fake-fopen
      run: cd fake-fopen && ./test.sh
    - name: Test fancy-file-io
      run: cd fancy-file-io && ./test.sh
    - name: Install Memkind
      run: sudo apt-get install -y libmemkind-dev
    - name: (Skipped--for now) Testing memkind-file-io
      run: echo # cd memkind-file-io && ./test.sh
